services:
  web:
    build:
      context: ./rusard_site
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rusard_site:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  postgres_data_dev: