version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ./rusard_site
      dockerfile: Dockerfile.prod
    command: gunicorn rusard_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=rusard.ch,www.rusard.ch
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=rusard.ch,www.rusard.ch
      - LETSENCRYPT_EMAIL=contact@rusard.ch
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_DEFAULT_REDIRECT=true
      - DEFAULT_HOST=rusard.ch
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d  #FIX use project vhost overrides
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro  #FIX ensure proxy size limit applied
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d  #FIX share same vhost overrides
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  acme:
