services:
  web:
    build:
      context: ./rusard_site
      dockerfile: Dockerfile.prod
    command: gunicorn rusard_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./rusard_site:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=rusard.ch,www.rusard.ch
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=rusard.ch,www.rusard.ch
      - LETSENCRYPT_EMAIL=contact@rusard.ch
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    environment:
      - ENABLE_DEFAULT_REDIRECT=true
      - DEFAULT_HOST=rusard.ch
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: docker-gen
    restart: always
    command: >-
      -notify-sighup nginx-proxy
      -watch
      -wait 5s:30s
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - docker-gen

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
  nginx_conf:
