#docker-compose.prod.yml
services:
  web:
    build:
      context: ./rusard_site
      dockerfile: Dockerfile.prod
    command: gunicorn rusard_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    environment:
      - VIRTUAL_HOST=rusard.ch,www.rusard.ch
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=rusard.ch,www.rusard.ch
      - LETSENCRYPT_EMAIL=contact@rusard.ch
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    environment:
      - ENABLE_DEFAULT_REDIRECT=true
      - DEFAULT_HOST=rusard.ch
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    env_file:
      - ./.env.prod.proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=contact@rusard.ch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: