services:
  web:
    build: .
    image: site-rusard:latest
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - SECRET_KEY=VotreCléSecrèteIci
      DEBUG: "1"
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

volumes:
  postgres_data: